export default function PrivacyPolicy() {
  return (
    <div className="mx-auto max-w-3xl p-4">
      <main className="space-y-6">
        <h1 className="text-3xl font-bold text-gray-900">
          Saiye - Privacy Policy
        </h1>
        <p className="text-base leading-relaxed text-gray-700">
          <em className="italic">Effective date: 2026-09-04</em>
        </p>
        <p className="text-base leading-relaxed text-gray-700">
          <strong>In short:</strong> Saiye is self-hosted, open-source
          software. When you run Saiye, your data lives on your own server and
          stays under your control. We do not operate a hosted service and do
          not collect your data.
        </p>
        <h2 className="text-lg font-semibold text-gray-900">1. Scope</h2>
        <p className="text-base leading-relaxed text-gray-700">
          This policy describes the privacy practices of the Saiye software.
          Because Saiye is self-hosted, you act as the operator of your own
          instance and are responsible for the data practices of your
          deployment.
        </p>
        <h2 className="text-lg font-semibold text-gray-900">
          2. Data Storage and Ownership
        </h2>
        <p className="text-base leading-relaxed text-gray-700">
          All content you save with Saiye — links, notes, images, PDFs, tags,
          and highlights — is stored on the infrastructure you choose. It is
          never sent to us, and we have no access to it.
        </p>
        <h2 className="text-lg font-semibold text-gray-900">
          3. Telemetry and Tracking
        </h2>
        <p className="text-base leading-relaxed text-gray-700">
          Saiye does not include telemetry, analytics, or third-party tracking.
          If you expose your instance to the public internet, standard server
          logs may be generated by your own infrastructure; those logs are
          yours to manage.
        </p>
        <h2 className="text-lg font-semibold text-gray-900">
          4. Third-Party Services
        </h2>
        <p className="text-base leading-relaxed text-gray-700">
          Optional features — such as AI-powered tagging or summarization —
          work only when you configure them with your own credentials for
          third-party providers. When you do, requests are sent directly from
          your instance to those providers under their terms and privacy
          policies. Saiye works without any third-party provider if you prefer
          not to use them.
        </p>
        <h2 className="text-lg font-semibold text-gray-900">
          5. Changes to This Policy
        </h2>
        <p className="text-base leading-relaxed text-gray-700">
          We may update this Privacy Policy from time to time. Changes will be
          published on this page with an updated effective date.
        </p>
        <h2 className="text-lg font-semibold text-gray-900">6. Contact Us</h2>
        <p className="text-base leading-relaxed text-gray-700">
          For privacy questions about the Saiye project, open an issue in the{" "}
          <a
            href="https://github.com/adrenalineinmyveins/karakeep"
            target="_blank"
            rel="noreferrer"
            className="text-blue-600 hover:underline"
          >
            GitHub repository
          </a>
          .
        </p>
      </main>
    </div>
  );
}
